// Generated with ReportLab; synthetic test token, not a credential.
#ifndef QR_FIXTURES_H
#define QR_FIXTURES_H
static const char expected_token[] = "AbCdEfGhIj0123456789";
static const char encoded_token[] = "v1.NgchByQLagcrDEVCUVJAXFlZFUk";
static const char legacy_payload[] = "https://webcam.connect.prusa3d.com/?token=AbCdEfGhIj0123456789&lang=de";
static const char *const legacy_matrix[] = {
  "XXXXXXX...XX...XXX...XXXX.X...XXXXXXX",
  "X.....X..X..X...X...X....X.XX.X.....X",
  "X.XXX.X.X..XX.XXX....X.X..XXX.X.XXX.X",
  "X.XXX.X.X.XX.X.X.XX...X..XXX..X.XXX.X",
  "X.XXX.X.XXXX.XXXXXXXX.XX....X.X.XXX.X",
  "X.....X.XX.X.X..XX..XXX.XXXX..X.....X",
  "XXXXXXX.X.X.X.X.X.X.X.X.X.X.X.XXXXXXX",
  "........X..XXX...XXXXXX.X...X........",
  "X.XXXXX..X..X...X..X..X.XX..X.XXXXX..",
  "XXXX.X.X...X..XX.XX.XX.X.XX....X.X.X.",
  "....XXX..X..X..XXX.X.XX.XXXX.XXX..XXX",
  ".XX.XX.X...X.XXX...XXXXX..XXXX..X...X",
  "XX..X.XX.X.XXX.XXXXX..XX.XXX.XXXXXXXX",
  "XX.....XX.X...X....XXXXX.......X....X",
  ".X....XXX.X..X.X..X.XXX.XXXXX..XXX.XX",
  "X..X.X...X.XXX..X..X.X.X..XXX..XX....",
  "XXX.X.XXX.XXXXX...X.X.XXXX..X.X...X.X",
  ".X.XX....X.X.X.XXX...X.X.XX..X.X...X.",
  "..X.XXXXXX.X.....X..X....XXXXXX..X.XX",
  "..X..X..XX....X.X....XX.X....XX.X...X",
  "X.XX.XXXXX...X...X....X.XXXX.XX.XX...",
  "X...X..XXX...XX.XX.XXX.XXX..X....X...",
  ".XXXXXXXXX..XXXXXX...XX.X..XX.XXXX.XX",
  "..XX...X...X...XXXXXXXX....X..XXX..XX",
  "XX..X.XX...XXXXXX..X.X..XX.XX.X.X.X.X",
  "X...XX.XXX..X..X..X.XX.X.XX..X.X.....",
  "X.XX.XXXX.XX.X.XX..X.X..XXXX..XXX..XX",
  "X.XXX.....X.X.XX..XXXXX........X.....",
  "X.....XX.XXXXXXX.X.X...X.XXXXXXXXXXXX",
  "........XX...XX.X.XX..XX.X.XX...XX..X",
  "XXXXXXX..X..X.XXX.X...X.....X.X.X.XXX",
  "X.....X.XX..........X..XX.X.X...XX.XX",
  "X.XXX.X.XXXX.XX...X.XXX.XX.XXXXXX.XX.",
  "X.XXX.X.X.X.X.XXXX...X.X....XXX.X...X",
  "X.XXX.X.X..XXXX..X..X...X.XX.....XXXX",
  "X.....X.........X....XXX..X.X.X.X...X",
  "XXXXXXX.XXX..X...X....X.XXXX.XX.XX.XX",
};
static const char current_payload[] = "https://camera-service-webcam.prusa3d.com/#t=v1.NgchByQLagcrDEVCUVJAXFlZFUk";
static const char *const current_matrix[] = {
  "XXXXXXX.....XX....X.XX......X.XXXXXXX",
  "X.....X...X.XXX.XXXX.XX.XX.XX.X.....X",
  "X.XXX.X.XX..X..XX..XXXXXX.X.X.X.XXX.X",
  "X.XXX.X.XXX.XX.X.X.XX.XXXXXXX.X.XXX.X",
  "X.XXX.X.X.X.XX..X.XXXX.X....X.X.XXX.X",
  "X.....X.X...XX....X.XX...X.XX.X.....X",
  "XXXXXXX.X.X.X.X.X.X.X.X.X.X.X.XXXXXXX",
  "........X..X.XXX....XXXX..XXX........",
  "X.XXXXX..X.X...X..X..XX.XXX...XXXXX..",
  "X....X...X..X..XX....XX...X.X..X..XX.",
  "XX.XXXX..X.X.X....X.X...X.XXX.XXX..XX",
  "...XXX...XXXXXX.X..X.X.X..XX.X......X",
  "XX.X.XXX.X..X....XXXX.X..XXX.XX.X.XXX",
  "XX.XX...XX.XXXX..X.XX..X..X....X...X.",
  "XXX...XX....XX.XXX...X...X.XX..XXX..X",
  "X..X.X.X.X.XXX.XXXXX.X.....X..XXX...X",
  ".XXXX.XXXX.XXXX.X....XXX..XX.XX.X.XXX",
  ".XX.X..X.X.X..XX..XXXX......X.XX...X.",
  "...XX.XXXXXX..XXXXX.X....X.X..XXXXXXX",
  "X.X.XX..XX..XX.X....XXX....XXXXX.X..X",
  ".X.XXXXX.....XXX.X..X.X.XXX..XX.X.X..",
  "X.X.X...XXXX.XX.X.XXXX.XX.X.X....X.X.",
  "X.X.XXX.XXXXX.XXX.X...X...XX..XXXX.XX",
  "X.XXX..X..XXXXX.X....X.........XX..X.",
  "XX..XXXXXX.XX.....X.X.X...XX.XX.X.X.X",
  "XX.X.X....X...XXX...XX.....XXX.X.X...",
  "X..XX.X....X.XX......X...XXXXX..X..XX",
  "X...XX.......X..X.XXXXXXX..X.XXXXX.X.",
  "X.XX..X.X.XXX.X..XX.X.X.XXXXXXXXXXX..",
  "........X.XX..X.XXXXX..X....X...XX...",
  "XXXXXXX..XX.X.XXXX...XX...X.X.X.X.X.X",
  "X.....X.X.X.X.X..XXXXX.XX.X.X...XX.X.",
  "X.XXX.X.X.XXX..XX..X.XX.X.XXXXXXX.XX.",
  "X.XXX.X.X.XX.XXX.XX.X.X..XX..XX.X.X.X",
  "X.XXX.X.X.XXXX.XXX...XX.X........XXXX",
  "X.....X...XXX.XX..XX.XXX..X.....X...X",
  "XXXXXXX.XXX.XXXX.X.X....XXX..XX.XX.XX",
};
#endif
